package com.inkforge.novel.web;

import com.inkforge.chapter.Chapter;
import com.inkforge.memory.StoryMemoryRepository;
import com.inkforge.novel.Novel;
import com.inkforge.novel.NovelRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.multipart;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * P6：保存续写草稿为正式章节的最小闭环 —— 追加成功（201）、序号/章节号递增、
 * 缺省标题自动生成、空内容 400、未知小说 404；
 * 保存不触发 Memory 提取（无 MemoryExtractionRecord），提取只能显式发起。
 */
@SpringBootTest(properties = {
        "inkforge.llm.provider=mock",
        "inkforge.llm.mock.delay-ms=0"})
@AutoConfigureMockMvc
class ChapterAppendControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private NovelRepository novelRepository;

    @Autowired
    private StoryMemoryRepository memoryRepository;

    private String novelId;

    @BeforeEach
    void seedNovel() throws Exception {
        byte[] novelBytes = getClass().getResourceAsStream("/fixtures/utf8_standard.txt").readAllBytes();
        String body = mockMvc.perform(multipart("/api/novels").file("file", novelBytes))
                .andExpect(status().isCreated())
                .andReturn().getResponse().getContentAsString(java.nio.charset.StandardCharsets.UTF_8);
        novelId = new tools.jackson.databind.ObjectMapper().readTree(body).get("id").asString();
        Novel novel = novelRepository.findById(novelId).orElseThrow();
        // fixture 至少 2 章且末章 chapterNo 非空，便于断言递增
        assertThat(novel.chapterCount()).isGreaterThanOrEqualTo(2);
    }

    @Test
    void appendChapterCreatesNextOrdinalKeepingChapterNoConvention() throws Exception {
        Novel before = novelRepository.findById(novelId).orElseThrow();
        int lastOrdinal = before.lastChapter().ordinal();
        Integer lastChapterNo = before.lastChapter().chapterNo(); // 楔子/番外可能为 null

        var result = mockMvc.perform(post("/api/novels/" + novelId + "/chapters")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"title\":\"续写的新章\",\"content\":\"林默收剑入鞘，转身离去。\"}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.ordinal").value(lastOrdinal + 1))
                .andExpect(jsonPath("$.title").value("续写的新章"))
                .andExpect(jsonPath("$.charCount").value("林默收剑入鞘，转身离去。".length()))
                .andReturn().getResponse()
                .getContentAsString(java.nio.charset.StandardCharsets.UTF_8);

        // chapterNo 沿用末章约定：非空则 +1，null 则保持 null
        tools.jackson.databind.JsonNode node =
                new tools.jackson.databind.ObjectMapper().readTree(result);
        if (lastChapterNo == null) {
            assertThat(node.get("chapterNo").isNull()).isTrue();
        } else {
            assertThat(node.get("chapterNo").asInt()).isEqualTo(lastChapterNo + 1);
        }

        mockMvc.perform(get("/api/novels/" + novelId + "/chapters/last"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content").value("林默收剑入鞘，转身离去。"));
    }

    @Test
    void blankTitleGetsAutoGeneratedDefault() throws Exception {
        Novel before = novelRepository.findById(novelId).orElseThrow();
        int expected = before.lastChapter().ordinal() + 2; // 展示用 = ordinal+1

        mockMvc.perform(post("/api/novels/" + novelId + "/chapters")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"content\":\"无标题的新章。\"}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.title").value("第" + expected + "章"));
    }

    @Test
    void blankContentIs400() throws Exception {
        mockMvc.perform(post("/api/novels/" + novelId + "/chapters")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"content\":\"\"}"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error").value("bad_request"));
    }

    @Test
    void missingBodyIs400() throws Exception {
        mockMvc.perform(post("/api/novels/" + novelId + "/chapters"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error").value("bad_request"));
    }

    @Test
    void unknownNovelIs404() throws Exception {
        mockMvc.perform(post("/api/novels/missing/chapters")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"content\":\"正文\"}"))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.error").value("not_found"));
    }

    @Test
    void savingChapterDoesNotTriggerMemoryExtraction() throws Exception {
        mockMvc.perform(post("/api/novels/" + novelId + "/chapters")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"content\":\"新的正式章节内容。\"}"))
                .andExpect(status().isCreated());

        // 保存只入 Canon：提取记录保持为空，Memory 未被触碰
        assertThat(memoryRepository.findExtractionRecords(novelId)).isEmpty();
        assertThat(memoryRepository.findCharacters(novelId)).isEmpty();
        assertThat(memoryRepository.findSummaries(novelId, 0, 100)).isEmpty();
        // 新章节已是小说的一部分（未来显式提取/构建时才会被使用）
        assertThat(novelRepository.findById(novelId).orElseThrow().lastChapter().content())
                .isEqualTo("新的正式章节内容。");
    }
}
